# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodayTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=2000)),
                ('desc', models.TextField()),
                ('language', models.CharField(max_length=250)),
                ('star_count', models.IntegerField()),
                ('fork_count', models.IntegerField()),
                ('today_star_count', models.IntegerField()),
            ],
        ),
    ]
