# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_todaytrend_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaytrend',
            name='rank',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
